<?php
define('CONST_PERM_CREATE_BID', 'create bid');
define('CONST_PERM_EDIT_BID', 'edit bid');

/**
 * Implements hook_permission().
 */
function bid_management_permission() {
  return array(
    CONST_PERM_CREATE_BID => array('title' => t('Create Bid')),
    CONST_PERM_EDIT_BID => array('title' => t('Edit Bid')),
  );
}

function bid_management_menu() {

  $items['add/bid'] = array(
    'title' => t('Caerus: Online System for Logging Opportunities'),
    'description' => 'Online System for Logging Opportunities',
    'page callback' => 'drupal_get_form',
    'access arguments' => array(TRUE),
    'page arguments' => array('bid_management_form'),
    'access arguments' => array(CONST_PERM_CREATE_BID),
    'type' => MENU_NORMAL_ITEM,
  );
    $items['bid/saved/%'] = array(
        'title' => t('Caerus: Online System for Logging Opportunities'),
        'page callback' => 'bid_saved_info',
        'page arguments' => array(2),
        'access arguments' => array(CONST_PERM_CREATE_BID),
        'type' => MENU_NORMAL_ITEM,
    );
  $items['bid/%/edit'] = array(
    'title' => t('bid_management edit details'),
    'page callback' => 'drupal_get_form',
    'access arguments' => TRUE,
    'page arguments' => array(
      'bid_management_form',
      1
    ),
    'access arguments' => array(CONST_PERM_CREATE_BID),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

function bid_wizard_steps() {
  return array(
    1 => array('form' => 'bid_wizard_step_1'),
    2 => array('form' => 'bid_wizard_step_2'),
    3 => array('form' => 'bid_wizard_step_3'),
    4 => array('form' => 'bid_wizard_step_4'),
    5 => array('form' => 'bid_wizard_step_5')
  );
}

/**
 * Implements hook-form_alter
 */
function bid_management_form_alter(&$form, &$form_state, $form_id)
{
}
/**
 * @param $form
 * @param $form_state
 * @param int $bid
 * @return fully formed form element.
 */
function bid_management_form($form, &$form_state, $bid = 0) {
    $edit = new stdClass();
  if ($bid != 0) {
    $query = db_select('bid_management', 'b');
    $query -> innerJoin('employee', 'emp', 'emp.eid = b.sales_owner');
    $query -> innerJoin('employee', 'e', 'e.eid = b.delivery_bid_owner');
    $query -> fields('b', array(
      'prosp_name',
      'opp_desc',
      'value',
      'horizontal',
      'sel_criteria',
      'competition',
      'opp_iss_date',
      'resp_due_date',
      'sales_owner',
      'delivery_bid_owner',
      'win_the',
      'core_team'
    ));
    $query -> condition('b.bid', $bid, '=');
  //  $form_state['loaded_defaults'] = $query -> execute() -> fetchObject();
  }
  //Step forms
  if (empty($form_state['step'])) {
    $form_state['step'] = 1;
    $form_state['step_information'] = bid_wizard_steps();
  }
  $step = &$form_state['step'];
  $form = $form_state['step_information'][$step]['form']($form, $form_state);
  if ($step > 2) {
    $form['prev'] = array(
      '#type' => 'submit',
      '#value' => t(''),
      '#name' => 'prev',
      '#submit' => array('bid_wizard_previous_submit'),
      '#limit_validation_errors' => array(),
    );
  }
  if ($step < count($form_state['step_information']) && $step  > 1)  {
    // The Next button should be included on every step
    $form['next'] = array(
      '#type' => 'submit',
      '#value' => t(''),
      '#name' => 'next',
      '#submit' => array('bid_wizard_next_submit'),
    );
  }
  else if($step == count($form_state['step_information'])) {
    $form['my-submit'] = array(
      '#type' => 'submit',
      '#value' => t('')
    );
  }
  if (function_exists($form_state['step_information'][$step]['form'] . '_validate')) {
    $form['next']['#validate'] = array($form_state['step_information'][$step]['form'] . '_validate');
  }
  $form['bid'] = array(
    '#type' => 'hidden',
    '#value' => $edit,
  );


  return $form;

}

function bid_wizard_step_1($form, &$form_state) {
  $form = array();
	  $path = url(drupal_get_path('module', 'bid_management') . '/scando.jpg', array('absolute' => TRUE));
  $form['help_text'] = array(
    '#type' => 'item',
    '#markup' => t('<div><img src="' . $path . '" style="padding-top:20px;width:200px;height:292px;"/></div>')
  );
  $form['dummy_text'] = array(
    '#type' => 'item',
    '#markup' => t("<p>Welcome to Caerus, Azur's online system for logging in your opportunities and launching the process of orchestrating a winning response
    powered by the Azur Touch. Named after the Greek God of opportunity, luck and favorable moments,
     it is the due measure that achieves the aim. Caerus will ensure that we approach every opportunity with a thoughtful
      and disciplined approach and involve the best talent thus increasing our chances of winning RFIs and RFPs.</p>
<p>Caerus. A habit of winning opportunities.</p>"),
  );
    $form['next-go'] = array(
        '#type' => 'submit',
        '#value' => t('<b style="color:white;">GO!</b>'),
        '#submit' => array('bid_wizard_next_submit'),
    );
  return $form;
}

function bid_wizard_step_2($form, &$form_state) {
//    $edit = isset($form_state['loaded_defaults']) ? $form_state['loaded_defaults']: '';
    $edit = NULL;
  $form = array();
  $path = url(drupal_get_path('module', 'bid_management') . '/wildoo.jpg', array('absolute' => TRUE));
  $industry_options = azur_get_taxonomy_terms('industries', 0, NULL);
  $industry_options[0] = t('Others');

    $form['progress'] = array(
        '#type' => 'item',
        '#markup' => '<div class="meter">
	<ol>
		<li class="active">
			<span class="step">1</span>
			<span class="stage">Opportunity</span>
		</li>
		<li>
			<span class="step">2</span>
			<span class="stage">Think</span>
		</li>
		<li>
			<span class="step">3</span>
			<span class="stage">Just the facts</span>
		</li>
	</ol>
</div>'
    );
  $form['help_text'] = array(
    '#type' => 'item',
    '#markup' => '<div><img src="' . $path . '" style="padding-top:20px;width:200px;height:292px;"/></div>',
  );
  $form['prosp_name'] = array(
    '#type' => 'textfield',
    '#title' => t('<b>1. Prospect Name</b>'),
      '#attributes' => array('placeholder' => t('The company that has issued the opportunity. Enter as how it is mentioned on the document')),
    '#size' => 100,
    '#maxlength' => 100,
    '#default_value' => isset($edit -> prosp_name) ? $edit -> prosp_name :'',
      '#required' => TRUE
  );
  $form['opp_desc'] = array(
    '#type' => 'textarea',
    '#title' => t('<b>2. Opportunity Description</b>'),
    '#default_value' => isset($edit -> opp_desc) ? $edit -> opp_desc : '',
      '#attributes' => array('placeholder' => t('What does the opportunity pertain to?
  What are the areas of focus? What tools and technologies is it about?
   What outcomes are they hoping to accomplish ?')),
      '#required' => TRUE
  );
  $form['value'] = array(
    '#type' => 'textfield',
    '#title' => t('<b> 3. Value (in $MM)</b>'),
    '#size' => 10,
    '#maxlength' => 10,
      '#attributes' => array('placeholder' => t('The potential deal size in USD million')),
    '#default_value' => isset($edit -> value) ? $edit -> value : '',
      '#required' => TRUE
  );
  $form['industry'] = array(
    '#type' => 'select',
    '#title' => t('<b> 4. Industry</b>'),
    '#options' => $industry_options,
    '#default_value' => isset($edit -> industry) ? $edit -> industry : NULL,
      '#required' => TRUE
  );
  $form['industry_others'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Industries'),
    '#maxlength' => '64',
    '#states' => array('visible' => array(':input[name="industry"]' => array('value' => 0), ), ),
    '#default_value' => isset($edit -> industry_others) ? $edit -> industry_others : '',
  );
  $path = url(drupal_get_path('module', 'bid_management') . '/avatar.png', array('absolute' => TRUE));
  $horizontal_options = azur_get_taxonomy_terms('horizontals', 0, NULL);
  $horizontal_options[0] = t('Others');
  $form['horizontal'] = array(
    '#type' => 'select',
    '#title' => t('<b> 5. Horizontals</b>'),
      '#options' => $horizontal_options,
    '#default_value' => isset($edit -> horizontal) ? $edit -> horizontal : NULL,
      '#required' => TRUE
  );
  $form['horiz_other'] = array(
    '#type' => 'textfield',
    '#title' => t('Other horizontals'),
    '#states' => array('visible' => array(':input[name="horizontal"]' => array('value' => 0), ), ),
    '#default_value' => isset($edit -> horiz_other) ? $edit -> horiz_other : '',
  );
  return $form;
}

function bid_wizard_step_3($form, &$form_state) {
    //$edit = isset($form_state['loaded_defaults']) ? $form_state['loaded_defaults']: '';
    $edit = NULL;
  $form = array();
    $form['progress'] = array(
        '#type' => 'item',
        '#markup' => '<div class="meter">
	<ol>
		<li class="active">
			<span class="step">1</span>
			<span class="stage">Opportunity</span>
		</li>
		<li class="active">
			<span class="step">2</span>
			<span class="stage">Think</span>
		</li>
		<li>
			<span class="step">3</span>
			<span class="stage">Just the facts</span>
		</li>
	</ol>
</div>'
    );
  $path = url(drupal_get_path('module', 'bid_management') . '/outadbox.jpg', array('absolute' => TRUE));
  $form['help_text'] = array(
    '#type' => 'item',
    '#markup' => '<div><img src="' . $path . '" style="padding-top:20px;width:200px;height:292px;position:relative;top:135px;"/></div>',
  );
    $form['bis_drivers'] = array(
        '#type' => 'textarea',
        '#title' => t('<b>6. Business Drivers </b>'),
        '#attributes' => array('placeholder' => t('What is pushing them towards outsourcing? What are the challenges they are facing? What technical trends are impacting them? What is happening in their industry or their ecosystem that is triggering this opportunity?')),
        '#required' => TRUE
    );
  $form['sel_criteria'] = array(
    '#type' => 'textarea',
    '#title' => t('<b> 7. Selection Criteria</b>'),
    '#default_value' => isset($edit -> sel_criteria) ? $edit -> sel_criteria : '',
      '#attributes' => array('placeholder' => t('What are the parameters based on which the vendor is going to be selected. This is either listed by them or our interpretations')),
      '#required' => TRUE
  );
  $form['win_the'] = array(
    '#type' => 'textarea',
    '#title' => t('<b> 8. Win Themes </b>'),
    '#default_value' => isset($edit -> win_the) ? $edit -> win_the : '',
      '#attributes' => array('placeholder' => t('What capability, showcase, profile or value system do we need to focus on to increase our chances of winning. List not more than 3-4')),
      '#required' => TRUE
  );
  $form['competition'] = array(
    '#type' => 'textarea',
    '#title' => t('<b> 9. Competition</b>'),
    '#default_value' => isset($edit -> competition) ? $edit -> competition : '',
      '#attributes' => array('placeholder' => t('List the complete universe (internal, external)')),
      '#required' => TRUE
  );
  return $form;
}

function bid_wizard_step_4($form, &$form_state) {
    //$edit = isset($form_state['loaded_defaults'])?$form_state['loaded_defaults'] : '';
    $edit = NULL;
  $form = array();
  $form['progress'] = array(
    '#type' => 'item',
    '#markup' => '<div class="meter">
	<ol>
		<li class="active">
			<span class="step">1</span>
			<span class="stage">Opportunity</span>
		</li>
		<li class="active">
			<span class="step">2</span>
			<span class="stage">Think</span>
		</li>
		<li class="active">
			<span class="step">3</span>
			<span class="stage">Just the facts</span>
		</li>
	</ol>
</div>'
  );
  $path = url(drupal_get_path('module', 'bid_management') . '/ynot.jpg', array('absolute' => TRUE));
  $form['help_text'] = array(
    '#type' => 'item',
    '#markup' =>'<div><img src="' . $path . '" style="padding-top:20px;width:200px;height:292px;"/></div>',
  );
  $form['opp_iss_date'] = array(
    '#type' => 'date_popup',
    '#date_label_position' => 'within',
    '#title' => t('<b> 10. Opportunity Issue Date</b>'),
      '#attributes' => array('placeholder' => 'MM/DD/YYYY'),
    '#default_value' => isset($edit -> opp_iss_date) && !empty($edit -> opp_iss_date) ? date('Y-m-d', $edit -> opp_iss_date) : "",
    '#date_format' => variable_get('date_format_date_only', 'm/d/Y'),
      '#required' => TRUE
  );
  $form['resp_due_date'] = array(
    '#type' => 'date_popup',
    '#title' => t('<b> 11. Response Due Date </b>'),
    '#date_label_position' => 'within',
      '#attributes' => array('placeholder' => 'MM/DD/YYYY'),
    '#default_value' => isset($edit -> resp_due_date) && !empty($edit -> resp_due_date) ? date('Y-m-d', $edit -> resp_due_date) : "",
    '#date_format' => variable_get('date_format_date_only', 'm/d/Y'),
      '#required' => TRUE
  );
  $form['sales_owner'] = array(
    '#type' => 'textfield',
    '#title' => t('<b> 12. Sales Owner</b>'),
      '#attributes' => array('placeholder' => t('The salesperson logging in this opportunity. Type the first letter for predictive input')),
    '#size' => 90,
    '#required' => TRUE,
    '#default_value' => isset($edit -> sales_owner) ? $edit -> sales_owner : '',
    '#autocomplete_path' => 'adminid/autocomplete',
      '#required' => TRUE
  );
  $form['delivery_bid_owner'] = array(
    '#type' => 'textfield',
    '#title' => t('<b> 13. Delivery Bid Owner</b>'),
      '#attributes' => array('placeholder' => t('Who are the delivery owners. You can enter more than one use comma to separate values')),
    '#size' => 90,
    '#required' => TRUE,
    '#autocomplete_path' => 'adminid/autocomplete',
    '#default_value' => isset($edit -> delivery_bid_owner) ? $edit -> delivery_bid_owner : '',
      '#required' => TRUE
  );

  $form['core_team'] = array(
    '#type' => 'textfield',
    '#title' => t('<b> 14. Core Team </b>'),
      '#attributes' => array('placeholder' => t('List the supporting cast members. Uses predictive input')),
    '#size' => 100,
    '#autocomplete_path' => 'adminid/autocomplete',
      '#required' => TRUE
  );
    $form['add_related_files'] = array(
        '#type' =>'plupload',
        '#title' => t('<b> 15. Add bid related files</b>'),
        '#upload_validators' => array('file_validate_extensions' => array('doc docx ppt pptx xls xlsx zip pdf')),
        '#autoupload' => TRUE,
    );
  return $form;
}

function bid_wizard_step_5($form, &$form_state) {
    $path = url(drupal_get_path('module', 'bid_management') . '/adoable.jpg', array('absolute' => TRUE));
    $form['help_text'] = array(
        '#type' => 'item',
        '#markup' =>'<div style="padding-bottom:50px;"><img src="' . $path . '" style="padding-top:20px;width:256px;height:300px;"/>'
    );
    $name = explode('[', $form_state['step_information'][4]['stored_values']['sales_owner']);
    $out =  '<p>Are you sure you want to create a bid from<b> ' . $form_state['step_information'][2]['stored_values']['prosp_name'] . '</b> for value of $<b>'
        . $form_state['step_information'][2]['stored_values']['value'] .'</b> Million ';
  $form['thank_you_page'] = array(
    '#type' => 'item',
    '#markup' =>$out,
  );
    return $form;
}

function bid_wizard_previous_submit($form, &$form_state) {
  $current_step = &$form_state['step'];
  $form_state['step_information'][$current_step]['stored_values'] = $form_state['values'];
  if ($current_step > 1) {
    $current_step--;
    $form_state['values'] = $form_state['step_information'][$current_step]['stored_values'];
  }
  $form_state['rebuild'] = TRUE;
}

function bid_wizard_next_submit($form, &$form_state) {
    if($form_state['step'] == 4){
        if(strtotime($form_state['values']['opp_iss_date']) > strtotime($form_state['values']['resp_due_date'])){
            form_set_error('resp_due_date',t('We are only human. Response due date cannot be earlier than opportunity issue date!'));
        }
    }
    if($form_state['step'] == 2){
        if(!is_numeric($form_state['values']['value'])){
            form_set_error('value',t('Please enter a numeric value.'));
        }
    }
  $current_step = &$form_state['step'];
  $form_state['step_information'][$current_step]['stored_values'] = $form_state['values'];

  if ($current_step < count($form_state['step_information'])) {
    $current_step++;
    if (!empty($form_state['step_information'][$current_step]['stored_values'])) {
      $form_state['values'] = $form_state['step_information'][$current_step]['stored_values'];
    }
    else {
      $form_state['values'] = array();
    }
    $form_state['rebuild'] = TRUE;
    // Force rebuild with next step.
    return;
  }
}

function bid_management_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'bid_management') . '/views',
  );
}

function bid_management_form_submit($form, &$form_state) {
    global $user;
  $horizon_tid = 0;
  $current_step = &$form_state['step'];
  $final_values = array();
  $form_state['step_information'][$current_step]['stored_values'] = $form_state['values'];
  foreach ($form_state['step_information'] as $key => $value) {
    foreach ($value['stored_values'] as $index => $val) {
      if ($index != 'form_build_id' && $index != 'form_token' && $index != 'form_id' && $index != 'next' && $index != 'prev' && $index != 'submit' && $index != 'op' && $index != 'industry_others' && $index != 'horiz_other') {
          $final_values[$index] = !empty($val) ? $val : '';
        if ($index == 'bid' && $val == NULL) {
          $final_values[$index] = !empty($val[$index]) ? $val[$index] : 0;
          unset($final_values[$index]);
        }
        if ($index == 'sales_owner' || $index == 'delivery_bid_owner' || $index == 'core_team') {
          if (strpos($val, ',')) {
            $split = explode(',', $val);
            for ($i = 0; $i < count($split); $i++) {
              $split[$i] = autocomplete_get_id_func($split[$i]);
            }
            $final_values[$index] = implode(',', $split);
          }
          else {
            $final_values[$index] = autocomplete_get_id_func($val);
          }
        }
      }
      if ($index == 'industry' && $val[$index] == 0) {
        $taxo = new stdClass;
        $taxo -> vid = azur_get_taxonomy_terms('industries', 0, NULL, 1);
        $taxo -> name = $val['industry_others'];
        $indus_tid = db_insert('taxonomy_term_data') -> fields(array(
          'vid' => $taxo -> vid,
          'name' => $taxo -> name
        )) -> execute();
        $final_values['industry'] = $indus_tid;
      }
      if ($index == 'horizontal' && $val[$index] == 0) {
        $taxo = new stdClass;
        $taxo -> vid = azur_get_taxonomy_terms('horizontals', 0, NULL, 1);
        $taxo -> name = $val['horiz_other'];
        $horizon_tid = db_insert('taxonomy_term_data') -> fields(array(
          'vid' => $taxo -> vid,
          'name' => $taxo -> name
        )) -> execute();
        $final_values['horizontal'] = $horizon_tid;
      }
        if($index == 'opp_iss_date' || $index == 'resp_due_date'){
            $final_values[$index] = strtotime($val);
        }
    }
  }
    drupal_mkdir('public://'.$final_values['prosp_name'],NULL,FALSE,NULL);
    foreach($final_values as $key => $row){
        if($key == 'add_related_files' && !empty($final_values['add_related_files'])){
            foreach($row as  $file_var){
                file_unmanaged_move($file_var['tmppath'],'public://'.$final_values['prosp_name'].'/'.$file_var['name']);
                $file = new stdClass;
                $file->uid = $user ->uid;
                $file->filename = $file_var['name'];
                $file->uri = 'public://'.$final_values['prosp_name'].'/'.$file_var['name'];
                $file->status = FILE_STATUS_PERMANENT;
                file_save($file);
                if(empty($final_values['fid'])){
                $final_values['fid'] = $file ->fid;
                }
                else{
                    $final_values['fid'] .=','. $file->fid;
                }
            }
        }
    }
    unset($final_values['add_related_files']);
    unset($final_values['next-go']);
    unset($final_values['my-submit']);
    unset($final_values['bid']);
  if (isset($final_values['bid'])) {
    $updated = db_update('bid_management') -> fields($final_values) -> condition('bid', $final_values['bid'], '=') -> execute();
  }
  else {
    $bid = db_insert('bid_management') -> fields($final_values) -> execute();
  }
  //USER Email.
    $core_team = explode(',',$final_values['core_team']);
  foreach ($core_team as  $eid) {
    $core_user = employee_return_user_details($eid);
    $message = ' You have been added to the core team for BID from'.$form_state['step_information'][2]['stored_values']['prosp_name'].
        'for a value of '.$form_state['step_information'][2]['stored_values']['value'].
        ' due on '.$form_state['step_information'][4]['stored_values']['resp_due_date'];
    $params = array(
      'body' => $message,
      'subject' => 'BID Management Request',
      'headers' => 'simple',
    );
    $to = $core_user -> mail;
    $site_email = variable_get('site_mail', '');
    drupal_mail('bid_management', 'bid_created', $to, language_default(), $params, $site_email, TRUE);
  }
    $name = explode('[', $form_state['step_information'][4]['stored_values']['sales_owner']);
    $msg = $name[0].','.$form_state['step_information'][2]['stored_values']['value'].','.
        $form_state['step_information'][2]['stored_values']['prosp_name'].','.
        $form_state['step_information'][4]['stored_values']['resp_due_date'];
    drupal_goto('bid/saved/'.$msg);
}
function     bid_saved_info($msg){
    $values = explode(',',$msg);
    $path = url(drupal_get_path('module', 'bid_management') . '/azur-logo.jpg', array('absolute' => TRUE));
    $msg= '<table class="form-table" style="border:1px solid; padding:20px;min-height:300px;">
    <tr style="margin-left:20px;margin-right:20px;">
    <td width="35%" style="padding: 20px;">
    <div><img src="' . $path . '" style="padding-top:20px;width:300px;height:110px;"/></div>
    </td>
    <td style="padding: 20px;font-size:18px">
    <p>Thank you <b>'.$values[0].'</b> for logging this $  <b>'.$values[1]
        .'</b> Million opportunity from <b>'.$values[2] .'</b> and due on <b>'.$values[3].'</b> Caerus is now in action.</p><p>Ka Ching!</p></td></tr></table>';
    return $msg;
}

function bid_management_mail($key, &$message, $params) {

  switch ($key) {
    case 'bid_created' :
      $message['subject'] = t($params['subject']);
      $message['body'][] = $params['body'];
      $message['headers']['Content-Type'] = 'text/html';
      $message['headers']['MIME-version'] = '1.0';
      break;
  }
}

//Horizontal types
function horizontal_type($typ = '') {
  static $types;
  if (!isset($types)) {
    $types = array(
      1 => t('Software service'),
      2 => t('Harware service'),
      3 => t('Others'),
    );
  }
  if (empty($typ)) {
    return $types;
  }
  elseif (isset($types[$typ])) {
    return $types[$typ];
  }
  else {
    return t('Invalid Option');
  }
}

/**
 * Implements hook_theme
 */
function bid_management_theme() {
  return array(
    'bid_management_form' => array(
      'render element' => 'form',
      'template' => 'bid-management-form'
    ),
  );
}
